source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', github: 'maccman/sinatra-contrib'
gem 'rack-standards'
gem 'unicorn'
gem 'erubis'
gem 'i18n'
gem 'activesupport'
gem 'rake'
gem 'builder'
gem 'json', '~> 1.7.7'
gem 'dotenv'

# Assets
gem 'sass'
gem 'compass'
gem 'sprockets'
gem 'sprockets-sass'
gem 'sprockets-memcache-store'
gem 'uglifier'
gem 'closure-compiler'
gem 'yui-compressor'
gem 'dalli'
gem 'memcachier'

# DB
gem 'sequel'
gem 'sinatra-sequel'
gem 'pg'

group :development do
  gem 'thin'
  gem 'debugger', require: 'ruby-debug'
end